//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_SOFT_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnSDSOFT : DbContext
    {
        public cnSDSOFT()
            : base("name=cnSDSOFT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enFelhasznalo> enFelhasznalok { get; set; }
        public virtual DbSet<enKinezet> enKinezetek { get; set; }
        public virtual DbSet<enTargy> enTargyak { get; set; }
        public virtual DbSet<enFelvettTargy> enFelvettTargyak { get; set; }
    }
}
