//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_SOFT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enFelhasznalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enFelhasznalo()
        {
            this.enFelvettTargy = new HashSet<enFelvettTargy>();
        }
    
        public int Id { get; set; }
        public string Jogosultsag { get; set; }
        public string Felhasznalonev { get; set; }
        public string Jelszo { get; set; }
        public string Nev { get; set; }
        public System.DateTime SzulDat { get; set; }
        public string Email { get; set; }
        public string Kinezet { get; set; }
        public string Lakcim { get; set; }
        public string Egyetem { get; set; }
    
        public virtual enKinezet enKinezet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enFelvettTargy> enFelvettTargy { get; set; }
    }
}
