//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_SOFT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enTargy
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Kredit { get; set; }
        public string Tipus { get; set; }
        public string Kovetelmeny { get; set; }
        public string VizsgaId { get; set; }
        public string PonthatarId { get; set; }
    
        public virtual enFelvettTargy enFelvettTargy { get; set; }
    }
}
