//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhasznalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Felhasznalo()
        {
            this.Targy = new HashSet<Targy>();
        }
    
        public int Id { get; set; }
        public string Felhasznalonev { get; set; }
        public string Jelszo { get; set; }
        public string Nev { get; set; }
        public string SzulDat { get; set; }
        public string Telefonszam { get; set; }
        public string Email { get; set; }
        public string Lakcim { get; set; }
    
        public virtual Kinezet Kinezet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Targy> Targy { get; set; }
    }
}
