//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinezet
    {
        public int Id { get; set; }
        public string Kulso { get; set; }
        public string Belso { get; set; }
    
        public virtual Felhasznalo Felhasznalo { get; set; }
    }
}
