//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SD_DBContainer : DbContext
    {
        public SD_DBContainer()
            : base("name=SD_DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Felhasznalo> Felhasznalok { get; set; }
        public virtual DbSet<Kinezet> Kinezetek { get; set; }
        public virtual DbSet<TargyInfo> TargyInfok { get; set; }
        public virtual DbSet<Targy> Targyak { get; set; }
    }
}
