//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Targy()
        {
            this.Beadando = new HashSet<Beadando>();
            this.ZH = new HashSet<ZH>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public string TargyId { get; set; }
    
        public virtual Felhasznalo Felhasznalo { get; set; }
        public virtual TargyInfo TargyInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beadando> Beadando { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZH> ZH { get; set; }
    }
}
