//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargyInfo
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Tipus { get; set; }
        public string Kredit { get; set; }
        public string Kovetelmeny { get; set; }
        public string Ponthatar { get; set; }
        public string Vizsga { get; set; }
    
        public virtual Targy Targy { get; set; }
    }
}
