//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targy
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string ZH { get; set; }
        public string Beadando { get; set; }
        public string Pluszpont { get; set; }
        public string TargyID { get; set; }
    
        public virtual Felhasznalo Felhasznalo { get; set; }
        public virtual TargyInfo TargyInfo { get; set; }
    }
}
